apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "2"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses:
    - https://familie-ba-mottak.dev-fss-pub.nais.io
    - https://familie-ba-mottak.dev.adeo.no
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad-api
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
    outbound:
      rules:
        - application: familie-ba-sak
          cluster: dev-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
  kafka:
    pool: nav-dev