apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 200m
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad-api
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-ba-sak
          cluster: prod-fss
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ba-mottak.nais.adeo.no
    - https://familie-ba-mottak.prod-fss-pub.nais.io
    - https://familie-ba-mottak.prod-fss.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering

  kafka:
    pool: nav-prod
