apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  envFrom:
    - secret: familie-baks-mottak
    - secret: familie-baks-mottak-unleash-api-token
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses:
    - https://familie-baks-mottak.intern.dev.nav.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad-api
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-baks-soknad-api
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: familie-ba-sak
          cluster: dev-gcp
        - application: familie-ks-sak
          cluster: dev-gcp
        - application: familie-dokument
          cluster: dev-gcp
        - application: familie-pdf
          cluster: dev-gcp
        - application: logging
          namespace: nais-system
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: familie-ba-infotrygd.dev-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_17 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-baks-mottak-17
        autoBackupHour: 2
        pointInTimeRecovery: false
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-baks-mottak
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
  kafka:
    pool: nav-dev

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
