no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/selvbetjening/.well-known/openid-configuration
      accepted_audience: aud-localhost
      # Kommenteres ut ved lokal testing av innsending av søknad
    #    azuread:
    #      discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    #      accepted_audience: ${CLIENT_ID}

  client:
    registration:
      ba-sak-clientcredentials:
        resource-url: ${FAMILIE_BA_SAK_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${BA_SAK_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ks-sak-clientcredentials:
        resource-url: ${FAMILIE_KS_SAK_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${KS_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: dummy
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic


credential:
  username: "srv-baks-mottak"
  password: "not-a-real-password"
funksjonsbrytere:
  kafka.enabled: false

logging:
  config: "classpath:logback-test.xml"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/familie-baks-mottak
    hikari:
      password: test
      username: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: none

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de"



#Brukes til tilgangskontroll av familie-ks-mottak-frontend
MOTTAK_ROLLE: group1
FAMILIE_INTEGRASJONER_API_URL: http://localhost:8085/api
FAMILIE_BA_SAK_API_URL: http://localhost:8090/api
FAMILIE_KS_SAK_API_URL: http://localhost:8083/api
KS_SAK_SCOPE: api://dev-gcp.teamfamilie.familie-ks-sak/.default
FAMILIE_DOKUMENT_API_URL: http://localhost:8082
FØDSELSHENDELSE_VENT_PÅ_TPS_MINUTTER: 1
FØDSELSHENDELSE_REKJØRINGSINTERVALL_MINUTTER: 1
KAFKA_BROKERS: http://localhost:9092
NORG2_API_URL: #mockes ut i test
STS_URL: "dummy"
PDL_URL: "dummy"
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

NAIS_APP_NAME: familie-baks-mottak

# Kreves for at unleash mock skal fungere:
UNLEASH_SERVER_API_URL: http://dummy/api/
UNLEASH_SERVER_API_TOKEN: dummy-token

# Disabler unleash her for å unngå feilmeldinger tilknyttet oppkobling når vi uansett mocker alle unleash-kall i testene.
unleash:
  enabled: false