spring:
  datasource:
    url: ${DB_JDBC_URL}

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de"

FØDSELSHENDELSE_VENT_PÅ_TPS_MINUTTER: 1
FØDSELSHENDELSE_REKJØRINGSINTERVALL_MINUTTER: 1

#Brukes til tilgangskontroll av familie-ks-mottak-frontend
JOURNALFOERINGHENDELSE_V1_TOPIC_AIVEN_URL: teamdokumenthandtering.aapen-dok-journalfoering

PDL_URL: https://pdl-api.dev-fss-pub.nais.io
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default
FAMILIE_INTEGRASJONER_API_URL: https://familie-integrasjoner.dev-fss-pub.nais.io/api
FAMILIE_INTEGRASJONER_SCOPE: api://dev-fss.teamfamilie.familie-integrasjoner/.default

FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.dev-fss-pub.nais.io
FAMILIE_BA_INFOTRYGD_SCOPE: api://dev-fss.teamfamilie.familie-ba-infotrygd/.default

FAMILIE_BA_SAK_API_URL: http://familie-ba-sak/api
BA_SAK_SCOPE: api://dev-gcp.teamfamilie.familie-ba-sak/.default

FAMILIE_KS_SAK_API_URL: http://familie-ks-sak/api
KS_SAK_SCOPE: api://dev-gcp.teamfamilie.familie-ks-sak/.default

NORG2_API_URL: https://norg2.dev-fss-pub.nais.io/norg2
FAMILIE_DOKUMENT_API_URL: http://familie-dokument/familie/dokument
FAMILIE_DOKUMENT_SCOPE: api://dev-gcp.teamfamilie.familie-dokument/.default


FAMILIE_PDF_URL: http://familie-pdf/
FAMILIE_PDF_SCOPE: api://dev-gcp.teamfamilie.familie-pdf/.default