spring:
  datasource:
    url: ${DB_JDBC_URL}

prosessering.rolle: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"

FØDSELSHENDELSE_VENT_PÅ_TPS_MINUTTER: 1440
FØDSELSHENDELSE_REKJØRINGSINTERVALL_MINUTTER: 180

JOURNALFOERINGHENDELSE_V1_TOPIC_AIVEN_URL: teamdokumenthandtering.aapen-dok-journalfoering
NORG2_API_URL: https://norg2.prod-fss-pub.nais.io/norg2
FAMILIE_DOKUMENT_API_URL: http://familie-dokument/familie/dokument
FAMILIE_DOKUMENT_SCOPE: prod-gcp:teamfamilie:familie-dokument

FAMILIE_BA_SAK_API_URL: http://familie-ba-sak/api
BA_SAK_SCOPE: api://prod-gcp.teamfamilie.familie-ba-sak/.default
FAMILIE_KS_SAK_API_URL: http://familie-ks-sak/api
KS_SAK_SCOPE: api://prod-gcp.teamfamilie.familie-ks-sak/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.prod-fss-pub.nais.io
FAMILIE_BA_INFOTRYGD_SCOPE: api://prod-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_INTEGRASJONER_API_URL: https://familie-integrasjoner.prod-fss-pub.nais.io/api
FAMILIE_INTEGRASJONER_SCOPE: api://prod-fss.teamfamilie.familie-integrasjoner/.default
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
FAMILIE_PDF_URL: http://familie-pdf/
FAMILIE_PDF_SCOPE: api://prod-gcp.teamfamilie.familie-pdf/.default