application:
  name: familie-baks-mottak

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  jackson:
    deserialization:
      # Allerede satt i felles, setter her slik at det gjelder for rest-params også
      FAIL_ON_UNKNOWN_PROPERTIES: false

logging:
  config: "classpath:logback-spring.xml"

retry.backoff.delay: 5000

prosessering:
  queue:
    capacity: 10
  pool:
    size: 2

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  health:
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

FAMILIE_INTEGRASJONER_API_URL: https://familie-integrasjoner.prod-fss-pub.nais.io/api
FAMILIE_DOKUMENT_API_URL: http://familie-dokument
FAMILIE_BA_INFOTRYGD_API_URL: http://familie-ba-infotrygd
FAMILIE_PDF_URL: http://familie-pdf
STS_URL: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
PDL_URL: http://pdl-api.pdl
ACCEPTEDAUDIENCE: dummy
