apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  envFrom:
    - secret: familie-baks-mottak
    - secret: familie-baks-mottak-unleash-api-token
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 2Gi
      cpu: 50m
  ingresses:
    - https://familie-baks-mottak.intern.nav.no
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad-api
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-baks-soknad-api
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: prod-gcp
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: familie-ba-sak
          cluster: prod-gcp
        - application: familie-ks-sak
          cluster: prod-gcp
        - application: familie-dokument
          cluster: prod-gcp
        - application: familie-baks-dokgen
          cluster: prod-gcp
      external:
        - host: kafka-schema-registry.nais.adeo.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-ba-infotrygd.prod-fss-pub.nais.io
        - host: familie-ks-infotrygd.prod-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-baks-mottak
        autoBackupHour: 2
        pointInTimeRecovery: true
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: familie-baks-mottak
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering

  kafka:
    pool: nav-prod

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
