name: Build-Dependabot
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-ba-mottak:${{ github.sha }}
  IMAGE_UTEN_TAG: docker.pkg.github.com/navikt/familie-ba-mottak/familie-ba-mottak

jobs:
  deploy-to-dev:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Dependabot-bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml
