name: Build-Deploy-Preprod
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
  merge_group:

jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          mvn antrun:run@ktlint
  build-dev:
    if: github.event.pull_request.draft == false
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - run: echo "event navn er:" ${{ github.event_name }} ${{ github.event.action }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v4'
        if: github.event_name != 'merge_group'
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco/
          retention-days: 2

      - name: Add coverage to PR
        id: jacoco
        if: github.event_name != 'merge_group'
        uses: madrapps/jacoco-report@v1.7.0
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: Code Coverage

      - uses: nais/docker-build-push@v0
        id: docker-push
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy-dev:
    if: github.event.pull_request.draft == false
    name: Deploy to dev-gcp
    needs: [build-dev]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp team namespace
        if: (github.event.pull_request.user.login != 'dependabot[bot]' && github.event_name != 'merge_group')
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml
          VAR: image=${{ needs.build-dev.outputs.image }}
