name: 'Remove Old Images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  remove-images:
    name: 'Remove old images'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-ba-mottak'
          package-type: 'container'
          min-versions-to-keep: 5
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-baks-mottak'
          package-type: 'container'
          min-versions-to-keep: 5
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-baks-mottak/familie-baks-mottak'
          package-type: 'container'
          min-versions-to-keep: 5